# Multi-View-Majority-Vote-Learning-Algorithms-Direct-Minimization-of-PAC-Bayesian-Bounds

In [1]:
import numpy as np
from sklearn.utils import check_random_state
from sklearn.preprocessing import MinMaxScaler
RAND = check_random_state(42)
import torch
import torch.nn as nn
from torch.autograd import Variable
from torch.nn.parameter import Parameter
from collections import OrderedDict
import torch.nn.functional as F
from torch.utils.data import DataLoader,Dataset
from mvlearn.datasets import load_UCImultifeature
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")


from dNDF import MultiViewBoundsDeepNeuralDecisionForests


from mvb import RandomForestClassifier as RFC


# Multi-view dataset : Nhanes 4 views https://wwwn.cdc.gov/nchs/nhanes/continuousnhanes/overview.aspx?BeginYear=2017
from data.datasets import (Nhanes, 
                           train_test_split,
                           train_test_merge)

In [2]:
mv_data, labels = load_UCImultifeature()
np.unique(labels)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [3]:
scaler = MinMaxScaler()
for i in range(len(mv_data)):
    mv_data[i] = scaler.fit_transform(mv_data[i])

In [4]:
mvb = MultiViewBoundsDeepNeuralDecisionForests(nb_estimators=3, nb_views=len(mv_data), depth =3,used_feature_rate=0.8)

In [5]:
mvb.fit(mv_data,labels)

MultiViewBoundsDeepNeuralDecisionForests(depth=3, nb_estimators=3, nb_views=6,
                                         posterior=array([0.33333333, 0.33333333, 0.33333333]),
                                         used_feature_rate=0.8)

In [6]:
posterior_Qv , posterior_rho = mvb.optimize_rho('Lambda',delta=0.05, eps=10**-9)

[[0.61780105 0.60645161 0.52574526]
 [0.71774194 0.53825503 0.46473029]
 [0.64931507 0.64323607 0.46311475]
 [0.43265306 0.37061995 0.26387009]
 [0.42496494 0.33149171 0.36351531]
 [0.4973262  0.44966443 0.52168022]]
Bound: tensor(1.0065, dtype=torch.float64, grad_fn=<AddBackward0>)
Upd: tensor(1.0065, dtype=torch.float64, grad_fn=<AddBackward0>)
Différence: tensor(2.0000e-09, dtype=torch.float64, grad_fn=<SubBackward0>)
Parameter containing:
tensor([0.3333, 0.3333, 0.3333], requires_grad=True)
Parameter containing:
tensor([0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667], requires_grad=True)
Avant normalisation et clampage: Parameter containing:
tensor([0.3332, 0.3332, 0.3332], requires_grad=True)
Avant normalisation et clampage: Parameter containing:
tensor([0.3332, 0.3332, 0.3333], requires_grad=True)
Avant normalisation et clampage: Parameter containing:
tensor([0.3332, 0.3332, 0.3333], requires_grad=True)
Avant normalisation et clampage: Parameter containing:
tensor([0.3333, 0.3333

In [7]:
print(posterior_Qv[0])
print(posterior_Qv[1])
print(posterior_Qv[2])
print(posterior_Qv[3])
print(posterior_Qv[4])
print(posterior_Qv[5])

Parameter containing:
tensor([0.3333, 0.3333, 0.3334], requires_grad=True)
Parameter containing:
tensor([0.3333, 0.3334, 0.3334], requires_grad=True)
Parameter containing:
tensor([0.3333, 0.3333, 0.3334], requires_grad=True)
Parameter containing:
tensor([0.3333, 0.3333, 0.3334], requires_grad=True)
Parameter containing:
tensor([0.3333, 0.3334, 0.3333], requires_grad=True)
Parameter containing:
tensor([0.3333, 0.3334, 0.3333], requires_grad=True)


In [9]:
posterior_rho

Parameter containing:
tensor([0.0167, 0.0167, 0.0167, 0.9833, 0.0167, 0.0167], requires_grad=True)